DROP DATABASE IF EXISTS COCINA;

CREATE DATABASE COCINA;
USE COCINA;

CREATE TABLE COCINERO (

   IdCocinero   INT AUTO_INCREMENT,
   Nombre      VARCHAR(100) NOT NULL,
   Apellido1   VARCHAR(100) NOT NULL,
   Apellido2   VARCHAR(100),
   PRIMARY KEY (IdCocinero)

);

CREATE TABLE CAMARERO (

   IdCamarero  INT AUTO_INCREMENT,
   Nombre      VARCHAR(100) NOT NULL,
   Apellido1   VARCHAR(100) NOT NULL,
   Apellido2   VARCHAR(100),
   PRIMARY KEY (IdCamarero)

);

CREATE TABLE MESA (

   IdMesa            INT AUTO_INCREMENT,
   NumMaxComensales  INT NOT NULL DEFAULT 1,
   Ubicacion         VARCHAR(100),   
   PRIMARY KEY (IdMesa)

);

CREATE TABLE CLIENTE (

   IdCliente     INT AUTO_INCREMENT,
   Nombre        VARCHAR(100) NOT NULL,
   Apellido1     VARCHAR(100) NOT NULL,
   Apellido2     VARCHAR(100),
   Observaciones VARCHAR(1000),
   PRIMARY KEY (IdCliente)
	
);

CREATE TABLE FACTURA (

   IdFactura     INT AUTO_INCREMENT,
	IdCliente     INT NOT NULL,
	IdCamarero    INT NOT NULL,	
   IdMesa        INT NOT NULL,
	FechaFactura  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (IdFactura)
	
);

ALTER TABLE FACTURA ADD CONSTRAINT FK_FACT_CLIENTE FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente);
ALTER TABLE FACTURA ADD CONSTRAINT FK_FACT_CAMARERO FOREIGN KEY (IdCamarero) REFERENCES CAMARERO(IdCamarero);
ALTER TABLE FACTURA ADD CONSTRAINT FK_FACT_MESA FOREIGN KEY (IdMesa) REFERENCES MESA(IdMesa);

CREATE TABLE DETALLEFACTURA (

   IdFactura         INT,
	IdDetalleFactura  INT AUTO_INCREMENT,
	IdCocinero        INT,
	Plato             VARCHAR(100) NOT NULL DEFAULT '',
	Importe           INT NOT NULL DEFAULT 0,
   -- 
	PRIMARY KEY (IdDetalleFactura)
	
);

ALTER TABLE DETALLEFACTURA ADD CONSTRAINT FK_DET_FACT_COCINERO FOREIGN KEY (IdCocinero) REFERENCES COCINERO(IdCocinero);
ALTER TABLE DETALLEFACTURA ADD CONSTRAINT FK_DET_FACT_FACTURA FOREIGN KEY (IdFactura) REFERENCES FACTURA(IdFactura);
